name: dental
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dotenv: ^4.2.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.2.4
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  url_launcher: ^6.3.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/fonts/
    - assets/images/
    - assets/animations/
    - assets/vectors/
  fonts:
    - family: Fredoka
      fonts:
        - asset: assets/fonts/Fredoka.ttf
    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoSans.ttf
        - asset: assets/fonts/NunitoSans-Italic-VariableFont_YTLC,opsz,wdth,wght.ttf
    - family: Varta
      fonts:
        - asset: assets/fonts/Varta-VariableFont_wght.ttf
    - family: Arsenal
      fonts:
        - asset: assets/fonts/Arsenal-Regular.ttf
        - asset: assets/fonts/Arsenal-Bold.ttf
        - asset: assets/fonts/Arsenal-Italic.ttf
        - asset: assets/fonts/Arsenal-BoldItalic.ttf